apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openlp-ctrl.fullname" . }}
  labels:
    {{- include "openlp-ctrl.labels" . | nindent 4 }}
data:
  ALLOWED_ORIGINS: {{ .Values.config.allowedOrigins | quote }}
  SERVER_HOST: {{ .Values.config.serverHost | quote }}
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
